INFO - 2025-02-13 00:00:44 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2025-02-13 00:00:50 --> ErrorException: Undefined array key "detalle_capacitacion"
in APPPATH\Controllers\NuevoController.php on line 1588.
 1 APPPATH\Controllers\NuevoController.php(1588): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "detalle_capacitacion"', 'C:\\xampp\\htdocs\\valoradorG2\\valorador\\app\\Controllers\\NuevoController.php', 1588)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord5('32')
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-02-13 00:00:53 --> ErrorException: Undefined array key "detalle_capacitacion"
in APPPATH\Controllers\NuevoController.php on line 1588.
 1 APPPATH\Controllers\NuevoController.php(1588): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "detalle_capacitacion"', 'C:\\xampp\\htdocs\\valoradorG2\\valorador\\app\\Controllers\\NuevoController.php', 1588)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord5('32')
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2025-02-13 00:04:08 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-02-13 00:04:16 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-02-13 00:08:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-02-13 11:44:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-02-13 11:44:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-02-13 12:19:05 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-02-13 12:19:06 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-02-13 12:19:17 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-02-13 12:19:25 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2025-02-13 13:18:59 --> ErrorException: Cannot redeclare App\Controllers\NuevoController::getDetailFormacionOfrecida()
in APPPATH\Controllers\NuevoController.php on line 1692.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2025-02-13 13:20:12 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-02-13 13:20:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-02-13 13:20:43 --> Registro con ID 34 no encontrado.
INFO - 2025-02-13 13:27:13 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-02-13 13:32:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-02-13 13:33:07 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-02-13 13:33:07 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-02-13 13:33:07 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-02-13 13:33:07 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-02-13 13:33:07 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-02-13 13:33:07 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2025-02-13 13:33:17 --> ErrorException: Undefined array key "id_formacion_ofrecida"
in APPPATH\Controllers\NuevoController.php on line 1693.
 1 APPPATH\Controllers\NuevoController.php(1693): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "id_formacion_ofrecida"', 'C:\\xampp\\htdocs\\valoradorG2\\valorador\\app\\Controllers\\NuevoController.php', 1693)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord6('34')
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2025-02-13 13:35:18 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-02-13 13:35:25 --> mysqli_sql_exception: Unknown column 'id_investigacion' in 'field list' in C:\xampp\htdocs\valoradorG2\valorador\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\valoradorG2\valorador\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `ac...', 0)
#1 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ac...')
#2 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ac...')
#3 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ac...', Array, false)
#4 C:\xampp\htdocs\valoradorG2\valorador\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\valoradorG2\valorador\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\valoradorG2\valorador\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\valoradorG2\valorador\app\Controllers\NuevoController.php(1698): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord6('34')
#9 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
#10 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\valoradorG2\valorador\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2025-02-13 13:35:25 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id_investigacion' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `id_detalle_investigacion`, `fecha`) VALUES (:id_investigacion:, :detalle_act_investigacion:, :id_detalle_investigacion:, :fecha:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\NuevoController.php(1698): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord6('34')
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-02-13 13:35:25 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id_investigacion' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `id_detalle_investigacion`, `fecha`) VALUES (\'34\', \'investigacion sobre ia-20-200\', \'7\', \'2025-02-13 13:35:25\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `id_detalle_investigacion`, `fecha`) VALUES (\'34\', \'investigacion sobre ia-20-200\', \'7\', \'2025-02-13 13:35:25\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `id_detalle_investigacion`, `fecha`) VALUES (:id_investigacion:, :detalle_act_investigacion:, :id_detalle_investigacion:, :fecha:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\NuevoController.php(1698): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord6('34')
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-02-13 13:35:25 --> [Caused by] mysqli_sql_exception: Unknown column 'id_investigacion' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `id_detalle_investigacion`, `fecha`) VALUES (\'34\', \'investigacion sobre ia-20-200\', \'7\', \'2025-02-13 13:35:25\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `id_detalle_investigacion`, `fecha`) VALUES (\'34\', \'investigacion sobre ia-20-200\', \'7\', \'2025-02-13 13:35:25\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `id_detalle_investigacion`, `fecha`) VALUES (\'34\', \'investigacion sobre ia-20-200\', \'7\', \'2025-02-13 13:35:25\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `id_detalle_investigacion`, `fecha`) VALUES (:id_investigacion:, :detalle_act_investigacion:, :id_detalle_investigacion:, :fecha:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\NuevoController.php(1698): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord6('34')
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-13 13:35:27 --> mysqli_sql_exception: Unknown column 'id_investigacion' in 'field list' in C:\xampp\htdocs\valoradorG2\valorador\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\valoradorG2\valorador\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `ac...', 0)
#1 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ac...')
#2 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ac...')
#3 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ac...', Array, false)
#4 C:\xampp\htdocs\valoradorG2\valorador\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\valoradorG2\valorador\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\valoradorG2\valorador\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\valoradorG2\valorador\app\Controllers\NuevoController.php(1698): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord6('34')
#9 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
#10 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\valoradorG2\valorador\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2025-02-13 13:35:27 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id_investigacion' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `id_detalle_investigacion`, `fecha`) VALUES (:id_investigacion:, :detalle_act_investigacion:, :id_detalle_investigacion:, :fecha:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\NuevoController.php(1698): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord6('34')
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-02-13 13:35:27 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id_investigacion' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `id_detalle_investigacion`, `fecha`) VALUES (\'34\', \'investigacion sobre ia-20-200\', \'7\', \'2025-02-13 13:35:27\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `id_detalle_investigacion`, `fecha`) VALUES (\'34\', \'investigacion sobre ia-20-200\', \'7\', \'2025-02-13 13:35:27\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `id_detalle_investigacion`, `fecha`) VALUES (:id_investigacion:, :detalle_act_investigacion:, :id_detalle_investigacion:, :fecha:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\NuevoController.php(1698): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord6('34')
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-02-13 13:35:27 --> [Caused by] mysqli_sql_exception: Unknown column 'id_investigacion' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `id_detalle_investigacion`, `fecha`) VALUES (\'34\', \'investigacion sobre ia-20-200\', \'7\', \'2025-02-13 13:35:27\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `id_detalle_investigacion`, `fecha`) VALUES (\'34\', \'investigacion sobre ia-20-200\', \'7\', \'2025-02-13 13:35:27\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `id_detalle_investigacion`, `fecha`) VALUES (\'34\', \'investigacion sobre ia-20-200\', \'7\', \'2025-02-13 13:35:27\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `id_detalle_investigacion`, `fecha`) VALUES (:id_investigacion:, :detalle_act_investigacion:, :id_detalle_investigacion:, :fecha:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\NuevoController.php(1698): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord6('34')
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2025-02-13 13:36:27 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-02-13 13:36:35 --> mysqli_sql_exception: Unknown column 'id_investigacion' in 'field list' in C:\xampp\htdocs\valoradorG2\valorador\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\valoradorG2\valorador\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `ac...', 0)
#1 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ac...')
#2 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ac...')
#3 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ac...', Array, false)
#4 C:\xampp\htdocs\valoradorG2\valorador\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\valoradorG2\valorador\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\valoradorG2\valorador\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\valoradorG2\valorador\app\Controllers\NuevoController.php(1698): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord6('34')
#9 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
#10 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\valoradorG2\valorador\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2025-02-13 13:36:35 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id_investigacion' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `fecha`) VALUES (:id_investigacion:, :detalle_act_investigacion:, :fecha:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\NuevoController.php(1698): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord6('34')
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-02-13 13:36:35 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id_investigacion' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `fecha`) VALUES (\'34\', \'investigacion sobre ia-20-200-100\', \'2025-02-13 13:36:35\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `fecha`) VALUES (\'34\', \'investigacion sobre ia-20-200-100\', \'2025-02-13 13:36:35\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `fecha`) VALUES (:id_investigacion:, :detalle_act_investigacion:, :fecha:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\NuevoController.php(1698): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord6('34')
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-02-13 13:36:35 --> [Caused by] mysqli_sql_exception: Unknown column 'id_investigacion' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `fecha`) VALUES (\'34\', \'investigacion sobre ia-20-200-100\', \'2025-02-13 13:36:35\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `fecha`) VALUES (\'34\', \'investigacion sobre ia-20-200-100\', \'2025-02-13 13:36:35\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `fecha`) VALUES (\'34\', \'investigacion sobre ia-20-200-100\', \'2025-02-13 13:36:35\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `fecha`) VALUES (:id_investigacion:, :detalle_act_investigacion:, :fecha:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\NuevoController.php(1698): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord6('34')
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-13 13:36:37 --> mysqli_sql_exception: Unknown column 'id_investigacion' in 'field list' in C:\xampp\htdocs\valoradorG2\valorador\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\valoradorG2\valorador\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `ac...', 0)
#1 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ac...')
#2 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ac...')
#3 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ac...', Array, false)
#4 C:\xampp\htdocs\valoradorG2\valorador\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\valoradorG2\valorador\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\valoradorG2\valorador\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\valoradorG2\valorador\app\Controllers\NuevoController.php(1698): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord6('34')
#9 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
#10 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\valoradorG2\valorador\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2025-02-13 13:36:37 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id_investigacion' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `fecha`) VALUES (:id_investigacion:, :detalle_act_investigacion:, :fecha:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\NuevoController.php(1698): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord6('34')
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-02-13 13:36:37 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id_investigacion' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `fecha`) VALUES (\'34\', \'investigacion sobre ia-20-200-100\', \'2025-02-13 13:36:37\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `fecha`) VALUES (\'34\', \'investigacion sobre ia-20-200-100\', \'2025-02-13 13:36:37\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `fecha`) VALUES (:id_investigacion:, :detalle_act_investigacion:, :fecha:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\NuevoController.php(1698): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord6('34')
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-02-13 13:36:37 --> [Caused by] mysqli_sql_exception: Unknown column 'id_investigacion' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `fecha`) VALUES (\'34\', \'investigacion sobre ia-20-200-100\', \'2025-02-13 13:36:37\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `fecha`) VALUES (\'34\', \'investigacion sobre ia-20-200-100\', \'2025-02-13 13:36:37\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `fecha`) VALUES (\'34\', \'investigacion sobre ia-20-200-100\', \'2025-02-13 13:36:37\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `fecha`) VALUES (:id_investigacion:, :detalle_act_investigacion:, :fecha:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\NuevoController.php(1698): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord6('34')
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-13 13:36:37 --> mysqli_sql_exception: Unknown column 'id_investigacion' in 'field list' in C:\xampp\htdocs\valoradorG2\valorador\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\valoradorG2\valorador\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `ac...', 0)
#1 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ac...')
#2 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ac...')
#3 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ac...', Array, false)
#4 C:\xampp\htdocs\valoradorG2\valorador\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\valoradorG2\valorador\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\valoradorG2\valorador\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\valoradorG2\valorador\app\Controllers\NuevoController.php(1698): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord6('34')
#9 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
#10 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\valoradorG2\valorador\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2025-02-13 13:36:37 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id_investigacion' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `fecha`) VALUES (:id_investigacion:, :detalle_act_investigacion:, :fecha:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\NuevoController.php(1698): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord6('34')
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-02-13 13:36:37 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'id_investigacion' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `fecha`) VALUES (\'34\', \'investigacion sobre ia-20-200-100\', \'2025-02-13 13:36:37\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `fecha`) VALUES (\'34\', \'investigacion sobre ia-20-200-100\', \'2025-02-13 13:36:37\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `fecha`) VALUES (:id_investigacion:, :detalle_act_investigacion:, :fecha:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\NuevoController.php(1698): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord6('34')
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-02-13 13:36:37 --> [Caused by] mysqli_sql_exception: Unknown column 'id_investigacion' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `fecha`) VALUES (\'34\', \'investigacion sobre ia-20-200-100\', \'2025-02-13 13:36:37\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `fecha`) VALUES (\'34\', \'investigacion sobre ia-20-200-100\', \'2025-02-13 13:36:37\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `fecha`) VALUES (\'34\', \'investigacion sobre ia-20-200-100\', \'2025-02-13 13:36:37\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_capacitacion` (`id_investigacion`, `detalle_act_investigacion`, `fecha`) VALUES (:id_investigacion:, :detalle_act_investigacion:, :fecha:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\NuevoController.php(1698): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord6('34')
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2025-02-13 13:36:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-02-13 13:37:08 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-02-13 13:37:12 --> Registro con ID 34 no encontrado.
ERROR - 2025-02-13 13:37:16 --> Registro con ID 34 no encontrado.
INFO - 2025-02-13 13:39:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-02-13 13:39:31 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-02-13 13:40:56 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-02-13 13:41:03 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-02-13 14:49:11 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
